[workspace]
members = [
  "classic-rcs",
  "next-generation-rcs",
  "optimizers",
  "lin-reg",
  "rc-plot",
  "common",
  "examples/sine",
  "examples/mackey_glass",
  "examples/doublescroll",
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "unwind"
