[package]
name = "reservoir_computer"
version = "0.1.5"
edition = "2021"
authors = ["Mathis Wellmann <wellmannmathis@gmail.com"]
license = "GNU AGPLv3"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4.14"
pretty_env_logger = "^0.4"
csv = "^1.1.6"
plotters = "^0.3.1"
thiserror = "^1"
nalgebra = { version = "^0.30", features = ["sparse"]}
nanorand = "^0.6"
