[package]
name = "lin-reg"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nalgebra.workspace = true

[dev-dependencies]
log.workspace = true
pretty_env_logger.workspace = true
round = "^0.1"
