[package]
name = "lin-reg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "^0.31.0"
log = "^0.4"

[dev-dependencies]
pretty_env_logger = "^0.4"
round = "^0.1"
